loaderVersion="[43,)"
license="LGPLv3"
[[mods]]
modId="sage"
version="${file.jarVersion}"
displayName="Sage"
logoFile="sage.png"
credits="doordash"
authors="Lodestar"
description='''
gaga
'''
[[dependencies.sage]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.sage]]
    modId="minecraft"
    mandatory=true
    ordering="NONE"
    side="BOTH"
    versionRange="[1.19.2,)"
[[dependencies.sage]]
    modId="lodestone"
    mandatory=true
    ordering="NONE"
    versionRange="[1.19.2-1.4,)"
    side="BOTH"
