modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
[[mods]]
modId="sage"
version="${file.jarVersion}"
displayName="Sage"
logoFile="sage.png"
credits="doordash"
authors="Lodestar"
description='''
gaga
'''
[[dependencies.sage]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sage]]
    modId="lodestone"
    mandatory=true
    versionRange="[1.19.2-1.4,)"
    ordering="NONE"
    side="BOTH"
